import 'reflect-metadata';
import { SchemaGenerator } from '../../src/core/schemaGenerator';
import { Model } from '../../src/core/model';
import { Field } from '../../src/decorators/model';

// ─── Models ───────────────────────────────────────────────────────────────────

class UserModel extends Model {
  static tableName = 'users';
  static schema = 'auth';
  static timestamps = false;

  @Field({ type: 'uuid', primary: true })                  id!: string;
  @Field({ type: 'string', required: true, unique: true }) email!: string;
  @Field({ type: 'string', required: true })               password!: string;
}

class PostModel extends Model {
  static tableName = 'posts';
  static softDelete = true;
  static timestamps = true;

  @Field({ type: 'serial', primary: true })                id!: number;
  @Field({ type: 'string', required: true, length: 300 })  title!: string;
  @Field({ type: 'text', nullable: true })                 body!: string | null;
  @Field({ type: 'boolean', default: false })              published!: boolean;
  @Field({ type: 'decimal', precision: 10, scale: 2 })    price!: string;
  @Field({ type: 'json' })                                 meta!: object;
  @Field({ type: 'date' })                                 publishedAt!: Date;
  @Field({ type: 'integer' })                              views!: number;
  @Field({ type: 'number' })                               rating!: number;
  @Field({ type: 'bigint' })                               reactions!: number;
  @Field({ type: 'enum', enumValues: ['draft', 'pub'] })   status!: string;
  @Field({ type: 'array' })                                tags!: string[];
}

class ProductModel extends Model {
  static tableName = 'products';
  static timestamps = false;

  @Field({ type: 'uuid', primary: true }) id!: string;
  @Field({ type: 'string' })              name!: string;
  @Field({ type: 'decimal' })             amount!: string; // no precision/scale → defaults
}

class MysqlModifiers extends Model {
  static tableName = 'mysql_mods';
  static timestamps = false;

  @Field({ type: 'uuid', primary: true })        id!: string;
  @Field({ type: 'string', unique: true })       code!: string;
  @Field({ type: 'boolean', default: false })    active!: boolean;
  @Field({ type: 'decimal' })                    price!: string;
  @Field({ type: 'enum' })                       raw!: string; // enum without enumValues
}

class MysqlUser extends Model {
  static tableName = 'users';
  static schema = 'app';
  static timestamps = false;

  @Field({ type: 'uuid', primary: true })                  id!: string;
  @Field({ type: 'string', required: true })               name!: string;
  @Field({ type: 'text' })                                 bio!: string;
  @Field({ type: 'enum', enumValues: ['admin', 'user'] })  role!: string;
  @Field({ type: 'integer' })                              age!: number;
  @Field({ type: 'number' })                               score!: number;
  @Field({ type: 'boolean' })                              active!: boolean;
  @Field({ type: 'date' })                                 createdAt!: Date;
  @Field({ type: 'decimal' })                              price!: string;
  @Field({ type: 'json' })                                 meta!: object;
  @Field({ type: 'bigint' })                               bigNum!: number;
  @Field({ type: 'serial' })                               seq!: number;
  @Field({ type: 'array' })                                tags!: string[];
}

class MysqlWithTimestamps extends Model {
  static tableName = 'mysql_ts';
  @Field({ type: 'uuid', primary: true }) id!: string;
}

class MysqlWithSoftDelete extends Model {
  static tableName = 'mysql_soft';
  static softDelete = true;
  static timestamps = false;
  @Field({ type: 'uuid', primary: true }) id!: string;
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('SchemaGenerator', () => {
  describe('PostgreSQL — basic output', () => {
    let output: string;

    beforeAll(() => {
      output = SchemaGenerator.generateDrizzleSchema([UserModel, PostModel, ProductModel], 'postgresql');
    });

    it('starts with the auto-generated comment', () => {
      expect(output).toMatch(/Auto-generated by Crudora/);
    });

    it('imports from drizzle-orm/pg-core', () => {
      expect(output).toContain("from 'drizzle-orm/pg-core'");
    });

    it('includes pgSchema import when a model has a schema', () => {
      expect(output).toContain('pgSchema');
    });

    it('declares the auth schema variable', () => {
      expect(output).toContain("const authSchema = pgSchema('auth')");
    });

    it('exports the UserModel table using the schema', () => {
      expect(output).toContain("export const userModelTable = authSchema.table('users'");
    });

    it('exports the PostModel table using pgTable (no schema)', () => {
      expect(output).toContain("export const postModelTable = pgTable('posts'");
    });

    it('includes all pg column types', () => {
      expect(output).toContain('serial(');
      expect(output).toContain('varchar(');
      expect(output).toContain('text(');
      expect(output).toContain('boolean(');
      expect(output).toContain('decimal(');
      expect(output).toContain('json(');
      expect(output).toContain('timestamp(');
      expect(output).toContain('integer(');
      expect(output).toContain('doublePrecision(');
      expect(output).toContain('bigint(');
      expect(output).toContain('.array()');
    });

    it('adds .notNull() for required columns', () => {
      expect(output).toContain('.notNull()');
    });

    it('adds .unique() for unique columns', () => {
      expect(output).toContain('.unique()');
    });

    it('adds .primaryKey() for primary columns', () => {
      expect(output).toContain('.primaryKey()');
    });

    it('adds .default() for columns with defaults', () => {
      expect(output).toContain('.default(false)');
    });

    it('adds createdAt and updatedAt for models with timestamps', () => {
      const postBlock = output.slice(output.indexOf('postModelTable'));
      expect(postBlock).toContain("timestamp('createdAt'");
      expect(postBlock).toContain("timestamp('updatedAt'");
    });

    it('adds deletedAt for soft-delete models', () => {
      const postBlock = output.slice(output.indexOf('postModelTable'));
      expect(postBlock).toContain("timestamp('deletedAt'");
    });

    it('does not add timestamps when timestamps=false', () => {
      const userBlock = output.slice(
        output.indexOf('userModelTable'),
        output.indexOf('postModelTable'),
      );
      expect(userBlock).not.toContain("timestamp('createdAt'");
    });

    it('respects custom decimal precision/scale', () => {
      expect(output).toContain('precision: 10, scale: 2');
    });
  });

  describe('PostgreSQL — no schema models', () => {
    it('uses pgTable when no schema defined', () => {
      const output = SchemaGenerator.generateDrizzleSchema([ProductModel], 'postgresql');
      expect(output).toContain("pgTable('products'");
      expect(output).not.toContain('pgSchema');
    });
  });

  describe('MySQL — basic output', () => {
    let output: string;

    beforeAll(() => {
      output = SchemaGenerator.generateDrizzleSchema([MysqlUser], 'mysql');
    });

    it('imports from drizzle-orm/mysql-core', () => {
      expect(output).toContain("from 'drizzle-orm/mysql-core'");
    });

    it('declares mysqlSchema variable', () => {
      expect(output).toContain("const appSchema = mysqlSchema('app')");
    });

    it('uses mysqlEnum for enum fields', () => {
      expect(output).toContain("mysqlEnum(");
    });

    it('uses int().autoincrement() for serial', () => {
      expect(output).toContain(".autoincrement()");
    });

    it('includes all mysql column types', () => {
      expect(output).toContain('varchar(');
      expect(output).toContain('int(');
      expect(output).toContain('double(');
      expect(output).toContain('boolean(');
      expect(output).toContain('datetime(');
      expect(output).toContain('decimal(');
      expect(output).toContain('json(');
      expect(output).toContain('bigint(');
    });

    it('uses json() for array type in MySQL', () => {
      // MySQL has no native array — falls back to json
      const output2 = SchemaGenerator.generateDrizzleSchema([MysqlUser], 'mysql');
      expect(output2).toContain('json(');
    });

    it('includes text() for text type in MySQL', () => {
      expect(output).toContain("text(");
    });
  });

  describe('MySQL — auto timestamps', () => {
    it('adds datetime createdAt and updatedAt when timestamps not false', () => {
      const out = SchemaGenerator.generateDrizzleSchema([MysqlWithTimestamps], 'mysql');
      expect(out).toContain("datetime('createdAt'");
      expect(out).toContain("datetime('updatedAt'");
    });
  });

  describe('MySQL — soft delete', () => {
    it('adds datetime deletedAt for soft-delete models', () => {
      const out = SchemaGenerator.generateDrizzleSchema([MysqlWithSoftDelete], 'mysql');
      expect(out).toContain("datetime('deletedAt'");
    });
  });

  describe('MySQL — column modifiers (unique, default, enum without values)', () => {
    it('adds .unique() and .default() in generated MySQL schema', () => {
      const out = SchemaGenerator.generateDrizzleSchema([MysqlModifiers], 'mysql');
      expect(out).toContain('.unique()');
      expect(out).toContain('.default(false)');
    });

    it('mysql enum without enumValues falls back to empty mysqlEnum call', () => {
      const out = SchemaGenerator.generateDrizzleSchema([MysqlModifiers], 'mysql');
      expect(out).toContain('mysqlEnum(');
    });
  });

  describe('PostgreSQL — decimal default precision/scale', () => {
    it('uses default precision:10 scale:2 when not specified', () => {
      const out = SchemaGenerator.generateDrizzleSchema([ProductModel], 'postgresql');
      expect(out).toContain('precision: 10, scale: 2');
    });
  });

  describe('multiple models — import deduplication', () => {
    it('does not repeat the same import identifier', () => {
      const output = SchemaGenerator.generateDrizzleSchema([UserModel, PostModel], 'postgresql');
      const importLine = output.split('\n').find((l) => l.startsWith('import {'));
      const identifiers = importLine!.replace(/import \{ | \} from.*/g, '').split(', ');
      const unique = new Set(identifiers);
      expect(identifiers.length).toBe(unique.size);
    });
  });

  describe('safe() — special characters in names', () => {
    class WeirdModel extends Model {
      static tableName = "tab'le";
      static timestamps = false;
      @Field({ type: 'string', primary: true }) id!: string;
    }

    it('escapes single quotes in table names', () => {
      const output = SchemaGenerator.generateDrizzleSchema([WeirdModel], 'postgresql');
      expect(output).toContain("tab\\'le");
    });
  });
});
