// Auto-generated by Crudora — do not edit manually
// Run: npx crudora generate-schema > src/db/schema.ts
//
// Example schema with multiple PostgreSQL schemas:
//
// import { pgTable, pgSchema, uuid, varchar, timestamp } from 'drizzle-orm/pg-core';
//
// const authSchema = pgSchema('auth');
//
// export const usersTable = authSchema.table('users', {
//   id: uuid('id').primaryKey(),
//   email: varchar('email', { length: 255 }).notNull().unique(),
//   password: varchar('password', { length: 255 }).notNull(),
//   createdAt: timestamp('createdAt', { mode: 'date' }).defaultNow().notNull(),
//   updatedAt: timestamp('updatedAt', { mode: 'date' }).defaultNow().notNull(),
// });
//
// export const postsTable = pgTable('posts', {
//   id: uuid('id').primaryKey(),
//   title: varchar('title', { length: 255 }).notNull(),
//   createdAt: timestamp('createdAt', { mode: 'date' }).defaultNow().notNull(),
//   updatedAt: timestamp('updatedAt', { mode: 'date' }).defaultNow().notNull(),
// });
